name: Auto-Tag

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request:
    types: [ "closed" ]

jobs:
  update_tag:
    permissions:
      contents: write

    uses: rwunderer/renovate/.github/workflows/reusable-auto-tag.yml@5a36bd45a5d1e38453cf1dff990ec214a0453d26 # main
    with:
      regex-pattern: "PACKER_VERSION=(\\d+\\.\\d+\\.\\d+)"
      tag-prefix: "v"
    secrets: inherit
