name: Auto-Tag

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request:
    types: [ "closed" ]

jobs:
  update_tag:
    permissions:
      contents: write

    uses: rwunderer/renovate/.github/workflows/reusable-auto-tag.yml@9eb2183ddfa45262543b33ee0f6a768c8bb680c2 # main
    with:
      regex-pattern: "PACKER_VERSION=(\\d+\\.\\d+\\.\\d+)"
      tag-prefix: "v"
    secrets: inherit
